language: python
sudo: false
python:
  - '3.7'
  - '3.8'
install:
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry pip install -e .
script:
  - py.test
after_success:
  - coveralls
